stages:
  - build_work
  - build_final

image: "${CI_REGISTRY_IMAGE}"


build-workdocs:     
    stage: build_work
    variables:
      TERM: xterm
    script:
        - make clean
        - make all
    artifacts:
      when: always
      paths:
          - main.log
          - thesis-workdoc.pdf
          - thesis-workdoc-print-annotate.pdf
      expire_in: 10 mins

build-finals:     
    stage: build_final
    variables:
      TERM: xterm
    script:
        - make clean
        - make all-final
    artifacts:
      when: always
      paths:
          - main.log
          - thesis-digital.pdf
          - thesis-print.pdf
      expire_in: 10 mins

